version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports: 
      - "8080:8080"
    volumes:
      - "$PWD/jenkins_data:/var/jenkins_home"
    networks:
      - net
  #rancher:
   # container_name: rancher
    #image: rancher/rancher
    #privileged: true
    #ports:
     # - "80:80"
   # volumes:
    #  - "$PWD/rancher:/var/lib/rancher-data"
    #networks:
     # - net
  remote_host:
    container_name: remote_host
    image: remote_host
    build:
      context: openssh
    networks:
      - net
networks:
  net:

